name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Fix Git permissions
        run: |
          sudo chmod -R u+w .git
          sudo chown -R $(whoami) .git
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_RIVER_065FAEF1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          output_location: "build" # Built app content directory - optional
        env:
          VITE_API_URL : ${{ secrets.VITE_API_URL }}
          VITE_OPENWEATHER_API_KEY : ${{ secrets.VITE_OPENWEATHER_API_KEY }}
          VITE_EMAIL_URL : ${{ secrets.VITE_EMAIL_URL }}
          VITE_REDIRECT_URL : ${{ secrets.VITE_REDIRECT_URL }}
          VITE_GOOGLE_MAPS_API_KEY :  ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
          VITE_CHATBOT_AGENT_ID :  ${{ secrets.VITE_CHATBOT_AGENT_ID }}
          VITE_CHATBOT_PROJECT_ID : ${{ secrets.VITE_CHATBOT_PROJECT_ID }}
          VITE_CLOUDINARY_UPLOAD_URL: ${{ secrets.VITE_CLOUDINARY_UPLOAD_URL }}
          VITE_CLOUDINARY_UPLOAD_PRESET: ${{ secrets.VITE_CLOUDINARY_UPLOAD_PRESET }}
          VITE_CODECOV_TOKEN: ${{secrets.VITE_CODECOV_TOKEN}}
          VITE_CLOUDINARY_UPLOAD_PRESET_FACILITIES: ${{ secrets.VITE_CLOUDINARY_UPLOAD_PRESET_FACILITIES }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_RIVER_065FAEF1E }}
          action: "close"
