name: Build and deploy Node.js app to Azure Web App - ireserve-bk-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r dist server.js package.json package-lock.json deploy/
          cd deploy
          zip -r ../release.zip .
          cd ..

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04BFD8A6AF874892BCF5FF2D7A20FFD9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AC72B4C9EB6C4AB19C6F00DDEA603C32 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E781B169298F4755BC524201FCBC85EE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ireserve-bk-frontend'
          slot-name: 'Production'
          package: .
